import { useState } from "react";
import { Footer } from "../components/Footer";
import { BILLING_AUTHORIZE_NET } from "../data/mockData";

type BillingTab = "authorize" | "paypal" | "stripe";

interface BillingSetupPageProps {
  isDarkMode?: boolean;
}

export function BillingSetupPage({ isDarkMode = false }: BillingSetupPageProps) {
  const [activeTab, setActiveTab] = useState<BillingTab>("authorize");
  const [apiLoginId, setApiLoginId] = useState(BILLING_AUTHORIZE_NET.apiLoginId);
  const [transactionKey, setTransactionKey] = useState(BILLING_AUTHORIZE_NET.transactionKey);
  const [paypalEmail, setPaypalEmail] = useState("");

  const primaryColor = isDarkMode ? "#DF2A57" : "#C70039";
  const cardBg = isDarkMode ? "#252830" : "#FFFFFF";
  const borderColor = isDarkMode ? "#333333" : "#E5E7EB";
  const textColor = isDarkMode ? "#E5E7EB" : "#333333";
  const mutedColor = isDarkMode ? "#9CA3AF" : "#666666";
  const inputBg = isDarkMode ? "#1A1C21" : "#FFFFFF";

  const tabs: { id: BillingTab; label: string }[] = [
    { id: "authorize", label: "Authorize.NET" },
    { id: "paypal", label: "PayPal" },
    { id: "stripe", label: "Stripe (Comming Soon)" },
  ];

  const inputStyle: React.CSSProperties = {
    width: "100%",
    height: "36px",
    padding: "0 10px",
    fontSize: "13px",
    border: `1px solid ${borderColor}`,
    borderRadius: "4px",
    background: inputBg,
    color: textColor,
    boxSizing: "border-box",
  };

  const labelStyle: React.CSSProperties = {
    display: "block",
    fontSize: "12px",
    color: mutedColor,
    marginBottom: "6px",
  };

  return (
    <div
      style={{
        flex: 1,
        display: "flex",
        flexDirection: "column",
        minHeight: 0,
        background: isDarkMode ? "#1A1C21" : "#F4F5F7",
      }}
    >
      <div style={{ flex: 1, padding: "24px", display: "flex", flexDirection: "column", gap: "20px" }}>
        <h1 style={{ fontSize: "20px", fontWeight: 600, color: primaryColor, margin: 0 }}>Billing Setup</h1>

        <div style={{ display: "flex", gap: "0", borderBottom: `1px solid ${borderColor}` }}>
          {tabs.map((tab) => {
            const isActive = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveTab(tab.id)}
                style={{
                  padding: "12px 20px",
                  fontSize: "13px",
                  fontWeight: isActive ? 600 : 400,
                  color: isActive ? primaryColor : mutedColor,
                  background: "transparent",
                  border: "none",
                  borderBottom: isActive ? `3px solid ${primaryColor}` : "3px solid transparent",
                  cursor: "pointer",
                  marginBottom: "-1px",
                }}
              >
                {tab.label}
              </button>
            );
          })}
        </div>

        <div
          style={{
            background: cardBg,
            border: `1px solid ${borderColor}`,
            borderRadius: "6px",
            padding: "24px",
            display: "flex",
            flexDirection: "column",
            gap: "20px",
          }}
        >
          {activeTab === "authorize" && (
            <>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px" }}>
                <div>
                  <label style={labelStyle}>API Login ID</label>
                  <input style={inputStyle} value={apiLoginId} onChange={(e) => setApiLoginId(e.target.value)} />
                </div>
                <div>
                  <label style={labelStyle}>Transaction Key</label>
                  <input style={inputStyle} value={transactionKey} onChange={(e) => setTransactionKey(e.target.value)} />
                </div>
              </div>
              <p style={{ margin: 0, fontSize: "12px", color: mutedColor, lineHeight: 1.6 }}>
                <strong>IMPORTANT:</strong> The API Login ID is different than your user login ID. The API Login ID is
                used for API transactions and is generated by Authorize.NET. Your user login ID is used to log into the
                Authorize.NET merchant interface.
              </p>
              <div>
                <button
                  type="button"
                  style={{
                    padding: "10px 24px",
                    background: primaryColor,
                    color: "#FFFFFF",
                    border: "none",
                    borderRadius: "4px",
                    fontSize: "13px",
                    fontWeight: 500,
                    cursor: "pointer",
                  }}
                >
                  Update Authorize.NET API Credentials
                </button>
              </div>
            </>
          )}

          {activeTab === "paypal" && (
            <>
              <div style={{ maxWidth: "480px" }}>
                <label style={labelStyle}>Your PayPal Email Address</label>
                <input
                  style={inputStyle}
                  value={paypalEmail}
                  onChange={(e) => setPaypalEmail(e.target.value)}
                  placeholder="Your PayPal Email Address"
                />
              </div>
              <div>
                <button
                  type="button"
                  style={{
                    padding: "10px 24px",
                    background: primaryColor,
                    color: "#FFFFFF",
                    border: "none",
                    borderRadius: "4px",
                    fontSize: "13px",
                    fontWeight: 500,
                    cursor: "pointer",
                  }}
                >
                  Save PayPal Configuration
                </button>
              </div>
            </>
          )}

          {activeTab === "stripe" && (
            <div
              style={{
                padding: "60px 20px",
                textAlign: "center",
                fontSize: "18px",
                color: mutedColor,
              }}
            >
              Coming Soon ™
            </div>
          )}
        </div>
      </div>
      <Footer isDarkMode={isDarkMode} />
    </div>
  );
}
